#lang racket
(define (print-lines . lines)
  (let loop((ls0 lines))
    (if (pair? ls0)
        (begin
         (display (car ls0))
         (newline)
         (loop (cdr ls0)))
        (newline))))
(print-lines '(1.2))
(struct posn (x y [z #:auto]))
(display posn)
(posn 1 2)
(newline)
(posn-x (posn 1 2))